version: '3.8'

services:
  bot:
    build: .
    container_name: thirty_five_coach_bot
    restart: always
    volumes:
      # Монтируем папку с базой данных на хост-систему
      - ./data:/app/data
      # Монтируем папку загрузок (фотографии пользователей и результаты)
      - ./downloads:/app/downloads
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
