version: '3.8'

services:
  bot:
    build: .
    container_name: thirty_five_coach_bot
    restart: always
    volumes:
      # Монтируем файл базы данных на хост-систему, чтобы данные не стирались при обновлении контейнера
      - ./coach_database.db:/app/coach_database.db
      # Монтируем папку загрузок (фотографии пользователей и результаты)
      - ./downloads:/app/downloads
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
